logging.level.root=INFO
logging.level.org.gatuninhas=INFO

spring.jpa.show-sql=false

management.endpoint.health.show-details=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false